# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Uni/CPE222/project/project.cache/wt [current_project]
set_property parent.project_path C:/Uni/CPE222/project/project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  C:/Uni/CPE222/project/project.srcs/sources_1/new/calculator_input.v
  C:/Uni/CPE222/project/project.srcs/sources_1/new/bcdDisplay.v
  C:/Uni/CPE222/project/project.srcs/sources_1/new/an_Control.v
  C:/Uni/CPE222/project/project.srcs/sources_1/new/afterImage.v
  C:/Uni/CPE222/project/project.srcs/sources_1/new/top_module.v
}
read_xdc C:/Users/HP/Desktop/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/HP/Desktop/Basys3_Master.xdc]

synth_design -top top_module -part xc7a35tcpg236-1
write_checkpoint -noxdef top_module.dcp
catch { report_utilization -file top_module_utilization_synth.rpt -pb top_module_utilization_synth.pb }
